airflow:
  service:
    type: NodePort
  image:
    repository: eu.gcr.io/taiyo-239217/airflow
    tag: fae4885
    pull_policy: IfNotPresent
  config:
  executor: KubernetesExecutor
  logs:
    persistence:
      accessMode: ReadWriteOnce
      ##
      ## Persistent Volume Storage Class
      ## If defined, storageClassName: <storageClass>
      ## If set to "-", storageClassName: "", which disables dynamic provisioning
      ## If undefined (the default) or set to null, no storageClassName spec is
      ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
      ##   GKE, AWS & OpenStack)
      # storageClass: default
      ##
      ## Existing claim to use
      existingClaim:
      existingClaimSubPath:
      ##
      ## Persistant storage size request
      size: 1Gi

  dags:
    persistence:
      enabled: false  # Persistence must be disabled when using git-sync
    git:
      # Play around with different repositories, branches and subpaths
      # subpath is the relative directory path in the git repository where
      # the dags can be found.
      url: https://github.com/imavishek/airflow
      username: imavishek
      password: '@abhipsha1996@'
      branch: master
      subpath: test-dags
  rbac:
    enabled: false


ingress:
  enabled: false

postgresql:
  enabled: true
  postgresUser: postgres
  postgresPassword: airflow
  postgresDatabase: airflow
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
